- name: install filebeat
  yum: name=filebeat state=latest enablerepo=elasticsearch
- name: config filebeat
  template: src=filebeat.yml.j2 dest=/etc/filebeat/filebeat.yml
  notify: restart filebeat
- name: start filebeat
  service: name=filebeat state=started
