- name: install nginx
  yum: name=nginx state=latest
- name: config nginx
  template: src=kibana.conf.j2 dest=/etc/nginx/conf.d/kibana.conf
  notify: restart nginx
- name: start nginx
  service: name=nginx state=started
