- name: install Elasticsearch
  yum: name=elasticsearch state=latest enablerepo=elasticsearch
- name: config Elasticsearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch
- name: config JVM
  template: src=jvm.options.j2 dest=/etc/elasticsearch/jvm.options
- name: start Elasticsearch
  service: name=elasticsearch state=started
- name: validate that elasticsearch is up and available
  uri:
    url: http://{{ ansible_default_ipv4.address }}:9200
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 2
